version: '3.1'
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-end-precification
    image: davjose/front-end-precification:v1.2
    restart: always
    ports:
      - "5173:5173"
